# Bernoulli random experiment 

In [9]:
#Misal percobaan melempar 1 mata uang  dan peluang  sukses sebesar = 50%

from scipy.stats import bernoulli
bernoulli.rvs(p=0.5, size = 1)



array([1])

In [ ]:
#keterangan : 
#p = peluang berhasil
#size = banyaknya mata uang yang di lempar


In [3]:
#Misal banyaknya mata uang yang dilempar di ubah menjadi 10
from scipy.stats import bernoulli
bernoulli.rvs(p=0.5, size = 10)


array([0, 1, 0, 1, 1, 1, 1, 0, 0, 0])

In [4]:
#Untuk menghitung jumlah head atau tail yang muncul 
#How many heads
sum(bernoulli.rvs(p=0.5, size = 10))


5

In [5]:

#another draw

sum(bernoulli.rvs(p=0.5, size = 10))


3

## Binomial random variable


In [6]:
#Misal percobaan melempar 1 mata uang dengan experiment sebanyak 10 kali, peluang berhasil = 50%.
from scipy.stats import binom
binom.rvs(n=10, p=0.5, size=1)




array([3])

In [ ]:
#keterangan : 
#n = banyaknya eksperimen
#p = peluang berhasil 
#size = banyaknya mata uang yang di lempar

In [7]:
#Misal percobaan melempar 10 mata uang dengan experiment sebanyak 10 kali, peluang berhasil = 50%.
from scipy.stats import binom
binom.rvs(n=10, p=0.5, size=10)



array([6, 5, 4, 7, 5, 5, 5, 5, 6, 5])

### Random generator seed


In [24]:

from scipy.stats import binom
import numpy as np


np.random.seed(42)

binom.rvs(n=10, p=0.5, size=1)

array([4])

In [7]:
from scipy.stats import binom
import numpy as np


np.random.seed(42)

binom.rvs(n=10, p=0.5, size=1)


array([4])

## Probability mass and distribution functions

### Probability mass functions

In [8]:
#Misal kita ingin mengetahui peluang mendapatkan tepat 2 kepala dengan eksperimen sebanyak 10 kali 
#dan peluang berhasil sebanyak 50%.

# Probability of 2 heads after 10 throws with a fair coin
from scipy.stats import binom
binom.pmf(k = 2, n = 10, p = 0.5)



0.04394531249999999

In [8]:
#Misal kita ingin mengetahui peluang mendapatkan tepat 5 kepala dengan eksperimen sebanyak 10 kali 
#dan peluang berhasil sebanyak 50%.

# Probability of 2 heads after 10 throws with a fair coin
from scipy.stats import binom
binom.pmf(k = 5, n = 10, p = 0.5)


0.24609375000000025

In [9]:
#Misal kita ingin mengetahui peluang mendapatkan tepat 50 kepala dengan eksperimen sebanyak 100 kali 
#dan peluang berhasil sebanyak 30%.

# Probability of 50 heads after 100 throws with p=0.3

from scipy.stats import binom
binom.pmf(k = 50, n = 100, p = 0.3)


1.30262271314453e-05

In [11]:
#Misal kita ingin mengetahui peluang mendapatkan tepat 65 kepala dengan eksperimen sebanyak 100 kali 
#dan peluang berhasil sebanyak 70%.

from scipy.stats import binom
binom.pmf(k = 65, n = 100, p = 0.7)




0.0467796823527298

### Cumulative distribution function (cdf) 

### Mencari niai peluang kurang dari

In [12]:
#Misal kita ingin mengetahui peluang mendapatkan 5 kepala atau kurang  dengan eksperimen sebanyak 10 kali 
#dan peluang berhasil  sebanyak 50%.

# Probability of 5 heads or less after 10 throws with a fair coin
from scipy.stats import binom
binom.cdf(k = 5, n = 10, p = 0.5)


0.6230468749999999

In [14]:
#Misal kita ingin mengetahui peluang mendapatkan 50 kepala atau kurang  dengan eksperimen sebanyak 100 kali 
#dan peluang berhasil  sebanyak 30%.

# Probability of 50 heads or less after 100 throws with p=0.3
from scipy.stats import binom

binom.cdf(k=50, n=100, p=0.3)

0.9999909653138043

### Mencari nilai peluang lebih dari 

In [15]:
#Misal kita ingin mengetahui peluang mendapatkan 59 kepala atau lebih   dengan eksperimen sebanyak 100 kali 
#dan peluang berhasil  sebanyak 70%.


# Probability of more than 59 heads after 100 throws with p=0.7

1-binom.cdf(k=59,n=100,p=0.7)


0.9875015928335618

### Expected Value  

Expected Value atau nilai harapan suatu variabel random menggambarkan nilai yang diharapkan akan terjadi dari suatu eksperimen random atau kecenderungan hasil yang akan tejadi.

### Arithmetic mean

Di python kita menggunakan scipy.stats.describe() untuk mendapatkan nilai rata-rata aritmatika

In [25]:
#Misal kita mencari nilai rata-rata dari  0 dan 1 
from scipy.stats import describe
describe([0,1]).mean

0.5

## Variance

Variance atau variansi digunakan untuk mendesripsikan tentang pusat sebaran.Nilai harapan tidak menjelaskan bentuk sebaran atau ragam suatu sebaran

Di python kita menggunakan scipy.stats.describe() untuk mendapatkan nilai variansi 

In [18]:

from scipy.stats import describe
describe ([0,1]).variance


0.5

# Binomial distribution expected value and variance

Di python kita menggunakan binom.stats() untuk mendapatkan nilai harapan dan variansi dari distribusi binomial,

E(X) = n × p


Var(X) = n × p × (1 − p)

In [21]:
#Menggunakan python
from scipy.stats import binom
binom.stats(n=10, p = 0.5)


(array(5.), array(2.5))

In [19]:
#Misal kita ingin mencari nilai harapan dan variansi dari eksperimen sebanyak 1 kali dan peluang= 0.3
from scipy.stats import binom
binom.stats(n=1, p = 0.3)


(array(0.3), array(0.21))

In [23]:
#Misal kita ingin mencari nilai harapan dan variansi dari eksperimen sebanyak 10 kali dan peluang= 0.5
from scipy.stats import binom
binom.stats(n=10, p = 0.5)

(array(5.), array(2.5))